source 'https://rubygems.org'
ruby '2.0.0'

gem 'sinatra', '~> 1.4.2'
gem 'sinatra-contrib', '~> 1.4.0'
gem 'thin', '~> 1.5.0'
gem 'shotgun', '~> 0.9'
gem 'haml', '~> 3.1.7'
gem 'rest-client', '~> 1.6.7'
gem 'dalli', '~> 2.6.2'
gem 'rack-cache', '~> 1.2'
gem 'memcachier', '~> 0.0.2'
gem 'sinatra-asset-pipeline', '~> 0.2.0'
gem 'sass', '~> 3.2.8'
gem 'yui-compressor', '~> 0.9.6'
